StylesPath = .vale/styles
MinAlertLevel = suggestion

Vocab = Portkey

[*.{md,mdx}]
BasedOnStyles = Vale

# Ignore spelling checks on old files that are no longer active
[virtual_key_old/**/*]
BasedOnStyles = 
vale.Editorial.Spelling = NO
